import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FCFBF6',
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
    paddingTop: Platform.OS === 'android' ? 40 : 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    color: '#8A713F', 
    letterSpacing: 0.5,
  },
  bellIcon: {
    color: '#656561',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    fontStyle: 'italic',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    color: '#6B582E',
  },
  sectionSubtitle: {
    fontSize: 10,
    color: '#B0AA9F',
    fontWeight: '600',
    letterSpacing: 1,
  },
  chartContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    paddingTop: 40,
    marginBottom: 35,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    height: 180,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  barCol: {
    alignItems: 'center',
    gap: 10,
  },
  barBg: {
    width: 28,
    borderRadius: 6,
  },
  barLabel: {
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  heroImageContainer: {
    width: '100%',
    height: 160,
    borderRadius: 20,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 35,
  },
  heroImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  heroImageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  changeHeroBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(237, 233, 222, 0.9)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
    gap: 8,
  },
  changeHeroBtnText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#6B582E',
  },
  audioContainer: {
    backgroundColor: '#FAFAF5',
    borderWidth: 1.5,
    borderColor: '#EAE6DB',
    borderStyle: 'dashed',
    borderRadius: 20,
    padding: 30,
    alignItems: 'center',
    marginBottom: 35,
  },
  audioIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#E5DDCB',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  audioTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#4A4A48',
    marginBottom: 6,
  },
  audioSub: {
    fontSize: 10,
    color: '#A8A39B',
    letterSpacing: 0.5,
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#EAE6DB',
  },
  dividerText: {
    marginHorizontal: 16,
    fontSize: 16,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    fontStyle: 'italic',
    color: '#8A713F',
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#A8A39B',
    letterSpacing: 1,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  textInput: {
    backgroundColor: '#F5F4EE',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 14,
    color: '#4A4A48',
  },
  textArea: {
    backgroundColor: '#F5F4EE',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 14,
    color: '#4A4A48',
    minHeight: 100,
    textAlignVertical: 'top',
  },
  keyWisdomContainer: {
    backgroundColor: '#F2EFE6',
    borderRadius: 20,
    padding: 20,
    marginBottom: 35,
  },
  keyWisdomInputGroup: {
    marginBottom: 15,
  },
  keyWisdomInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 14,
    color: '#4A4A48',
  },
  keyWisdomTextArea: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 14,
    color: '#A3A3A3',
    fontStyle: 'italic',
    minHeight: 80,
    textAlignVertical: 'top',
  },
  editorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  editorToolbar: {
    flexDirection: 'row',
    gap: 15,
    marginRight: 10,
  },
  bodyTextArea: {
    backgroundColor: '#F5F4EE',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
    fontSize: 15,
    color: '#4A4A48',
    minHeight: 250,
    textAlignVertical: 'top',
    marginBottom: 40,
  },
  publishBtn: {
    backgroundColor: '#9B7B3C',
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 18,
    gap: 10,
    marginBottom: 16,
    shadowColor: '#9B7B3C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },
  publishBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  draftBtn: {
    alignItems: 'center',
    paddingVertical: 12,
  },
  draftBtnText: {
    color: '#6B582E',
    fontSize: 14,
    fontWeight: '600',
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 15,
    paddingBottom: Platform.OS === 'ios' ? 30 : 15,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 10,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  navItem: {
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
  },
  navItemActive: {
    backgroundColor: '#F2EFE6',
  },
  navIcon: {
    marginBottom: 4,
  },
  navText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#A8A39B',
    letterSpacing: 0.5,
  },
  navTextActive: {
    color: '#6B582E',
  },
  draftsContainer: {
    flex: 1,
  },
  draftItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 5,
    elevation: 2,
  },
  draftItemLeft: {
    flex: 1,
  },
  draftDate: {
    fontSize: 10,
    color: '#B0AA9F',
    fontWeight: 'bold',
    marginBottom: 4,
  },
  draftTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4A4A48',
    marginBottom: 4,
  },
  draftSub: {
    fontSize: 12,
    color: '#A8A39B',
  },
  draftDeleteBtn: {
    padding: 10,
    backgroundColor: '#F5F4EE',
    borderRadius: 10,
  },
  draftEmptyText: {
    textAlign: 'center',
    marginTop: 40,
    color: '#A8A39B',
    fontStyle: 'italic',
  }
});
