import { StyleSheet, Platform, StatusBar } from 'react-native';

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#FAF8F3',
        paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 12,
    },
    iconButton: {
        padding: 4,
    },
    headerCenter: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        fontSize: 10,
        fontWeight: '700',
        color: '#8A8A8C',
        letterSpacing: 2,
        marginBottom: 6,
    },
    headerProgress: {
        width: 32,
        height: 2,
        backgroundColor: '#826930',
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    profileCircle: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#1A1A1D',
        marginLeft: 12,
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingTop: 16,
    },
    audioCard: {
        backgroundColor: '#F4ECE1',
        borderRadius: 20,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    playButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#826930',
        justifyContent: 'center',
        alignItems: 'center',
    },
    audioInfo: {
        flex: 1,
        marginLeft: 16,
    },
    audioTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    audioLabel: {
        fontSize: 10,
        fontWeight: '700',
        color: '#826930',
        letterSpacing: 1.5,
    },
    audioTime: {
        fontSize: 10,
        color: '#8A8A8C',
    },
    progressBarBg: {
        height: 3,
        backgroundColor: '#DFD8CC',
        borderRadius: 1.5,
        position: 'relative',
        justifyContent: 'center',
    },
    progressBarFill: {
        height: 3,
        backgroundColor: '#826930',
        borderRadius: 1.5,
        width: '35%',
    },
    progressBarDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#826930',
        position: 'absolute',
        left: '35%',
        marginLeft: -4,
    },
    mainImage: {
        width: '100%',
        height: 180,
        borderRadius: 24,
        marginBottom: 44,
    },
    verseSection: {
        alignItems: 'center',
        marginBottom: 44,
    },
    verseLabel: {
        fontSize: 10,
        fontWeight: '700',
        color: '#A3A3A3',
        letterSpacing: 3,
        marginBottom: 24,
    },
    verseQuote: {
        fontSize: 30,
        fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
        fontStyle: 'italic',
        color: '#1A1A1D',
        textAlign: 'center',
        lineHeight: 44,
        marginBottom: 20,
        paddingHorizontal: 16,
    },
    verseReference: {
        fontSize: 10,
        fontWeight: '700',
        color: '#A3A3A3',
        letterSpacing: 2,
    },
    blockquoteContainer: {
        flexDirection: 'row',
        marginBottom: 40,
        paddingLeft: 4,
    },
    blockquoteLine: {
        width: 2,
        backgroundColor: '#D1CDBF',
        marginRight: 20,
    },
    blockquoteText: {
        flex: 1,
        fontSize: 18,
        fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
        fontStyle: 'italic',
        color: '#4A4A48',
        lineHeight: 28,
    },
    bodyTextContainer: {
        marginBottom: 32,
    },
    bodyText: {
        fontSize: 15,
        color: '#4A4A48',
        lineHeight: 28,
        marginBottom: 24,
    },
    tagsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 20,
    },
    tagPill: {
        backgroundColor: '#EBE9DD',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        marginRight: 10,
        marginBottom: 10,
    },
    tagText: {
        fontSize: 10,
        fontWeight: '700',
        color: '#4A4A48',
        letterSpacing: 1,
    },
    bottomSpace: {
        height: 120,
    },
    floatingActionBar: {
        position: 'absolute',
        bottom: 30,
        left: 20,
        right: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.65)',
        borderRadius: 40,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        paddingHorizontal: 20,
        shadowColor: '#FFFFF',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.08,
        shadowRadius: 24,
        elevation: 8,
    },
    actionLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    actionText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#1A1A1D',
        marginLeft: 10,
    },
    actionDivider: {
        width: 1,
        height: 24,
        backgroundColor: '#F0F0F0',
        marginHorizontal: 16,
    },
    actionRight: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        justifyContent: 'flex-end',
    },
    actionIconOnly: {
        marginRight: 20,
    },
    reflectButton: {
        backgroundColor: '#826930',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 14,
        borderRadius: 24,
    },
    reflectButtonText: {
        color: '#FFFFFF',
        fontWeight: '700',
        fontSize: 13,
        marginLeft: 8,
    },
});
