import { StyleSheet, Platform, StatusBar } from 'react-native';

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#F8F6F0',
        paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    container: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingTop: 16,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 32,
    },
    headerTitle: {
        fontSize: 22,
        fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
        fontStyle: 'italic',
        fontWeight: 'bold',
        color: '#C19B36',
    },
    avatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#E5DCC5',
    },
    greetingContainer: {
        marginBottom: 24,
    },
    greetingUser: {
        fontSize: 30,
        fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
        fontWeight: 'bold',
        color: '#1A1A1D',
        marginBottom: 8,
    },
    greetingSub: {
        fontSize: 15,
        color: '#8A8A8C',
    },
    tabsContainer: {
        marginBottom: 32,
        maxHeight: 40,
    },
    tabsContent: {
        paddingRight: 24,
    },
    tabButton: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: '#F0EFE9',
        borderRadius: 20,
        marginRight: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    tabButtonActive: {
        backgroundColor: '#C59A3F',
    },
    tabText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#4A4A48',
    },
    tabTextActive: {
        color: '#FFFFFF',
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        padding: 24,
        marginBottom: 40,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.04,
        shadowRadius: 16,
        elevation: 4,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 22,
    },
    cardHeaderTitle: {
        fontSize: 11,
        fontWeight: '700',
        color: '#C59A3F',
        letterSpacing: 1.5,
    },
    listenButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FDF7E7',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 16,
    },
    listenText: {
        fontSize: 10,
        fontWeight: '700',
        color: '#C59A3F',
        marginLeft: 6,
        letterSpacing: 1,
    },
    quoteTitle: {
        fontSize: 24,
        fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
        color: '#1A1A1D',
        lineHeight: 34,
        marginBottom: 12,
    },
    quoteSub: {
        fontSize: 13,
        fontStyle: 'italic',
        color: '#8A8A8C',
        marginBottom: 24,
        letterSpacing: 0.5,
    },
    quoteBody: {
        fontSize: 15,
        fontStyle: 'italic',
        color: '#4A4A48',
        lineHeight: 24,
        marginBottom: 16,
    },
    quoteAuthor: {
        fontSize: 11,
        fontWeight: '700',
        color: '#8A8A8C',
        letterSpacing: 1,
        marginBottom: 28,
    },
    readMoreButton: {
        flexDirection: 'row',
        backgroundColor: '#C59A3F',
        borderRadius: 16,
        paddingVertical: 18,
        justifyContent: 'center',
        alignItems: 'center',
    },
    readMoreText: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 15,
    },
    notesSection: {
        marginBottom: 40,
    },
    notesTitle: {
        fontSize: 22,
        fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
        fontWeight: 'bold',
        color: '#1A1A1D',
        marginBottom: 12,
    },
    editorContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        borderWidth: 1,
        borderColor: '#EAE8E0',
        marginBottom: 28,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.04,
        shadowRadius: 16,
        elevation: 3,
    },
    inputWrapper: {
        position: 'relative',
        padding: 10,
        height: 390,
    },
    editorTextInput: {
        flex: 1,
        fontSize: 16,
        color: '#1A1A1D',
        lineHeight: 26,
        fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
        zIndex: 2,
    },
    watermark: {
        position: 'absolute',
        bottom: 9,
        right: 10,
        fontSize: 200,
        fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
        fontStyle: 'italic',
        fontWeight: 'bold',
        color: '#F8F6F0',
        zIndex: 1,
    },
    saveButtonBox: {
        backgroundColor: '#C59A3F',
        borderBottomLeftRadius: 14,
        borderBottomRightRadius: 14,
        borderTopRightRadius: 14,
        borderTopLeftRadius: 14,
        paddingVertical: 18,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center'
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontWeight: '700',
        fontSize: 14,
        letterSpacing: 1,
    },
    bottomSpace: {
        height: 120,
    },
    bottomTabBar: {
        position: 'absolute',
        bottom: 14,
        left: 20,
        right: 20,

        height: 60,
        paddingHorizontal: 10,

        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',

        borderRadius: 30,

        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.08,
        shadowRadius: 20,

        elevation: 8,
    },
    tabItem: {
        alignItems: 'center',
        paddingVertical: 12,
        flex: 1,
    },
    activeTabIndicator: {
        position: 'absolute',
        bottom: 12,
        width: 28,
        height: 4,
        backgroundColor: '#FFFFFF',
        borderBottomLeftRadius: 4,
        borderBottomRightRadius: 4,
    },
    tabItemText: {
        fontSize: 10,
        color: '#1F1F1F',
        marginTop: 6,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    tabItemTextActive: {
        color: '#C59A3F',
    }
});
