import { StyleSheet, Platform, StatusBar } from 'react-native';

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#F7F5EE',
        paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    container: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingTop: 16,
        paddingBottom: 24,
    },
    dismissButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 4,
    },
    dismissText: {
        fontSize: 10,
        fontWeight: '700',
        color: '#F87171',
        letterSpacing: 1.5,
        marginLeft: 6,
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    journalText: {
        fontSize: 10,
        fontWeight: '700',
        color: '#A8A8A8',
        letterSpacing: 2,
        marginRight: 8,
    },
    dot: {
        width: 8,
        height: 8,

        borderRadius: 8,
        backgroundColor: '#22C55E',
        color: '#15e00eff',
    },
    content: {
        flex: 1,
        paddingHorizontal: 24,
    },
    title: {
        fontSize: 34,
        fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
        fontWeight: 'bold',
        color: '#1A1A1D',
        marginBottom: 8,
    },
    titleUnderline: {
        width: 40,
        height: 2,
        backgroundColor: '#B5965A',
        marginBottom: 32,
    },
    editorContainer: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#EAE8E0',
        marginBottom: 32,
        overflow: 'hidden',
    },
    inputWrapper: {
        flex: 1,
        position: 'relative',
        padding: 20,
    },
    textInput: {
        flex: 1,
        fontSize: 18,
        color: '#4A4A48',
        lineHeight: 28,
        fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
        zIndex: 2,
    },
    watermark: {
        position: 'absolute',
        bottom: -20,
        right: 10,
        fontSize: 240,
        fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
        fontStyle: 'italic',
        fontWeight: 'bold',
        color: '#EFECE1',
        zIndex: 1,
        lineHeight: 240,
    },
    bottomSection: {
        marginBottom: 32,
    },
    divider: {
        width: '100%',
        height: 1,
        backgroundColor: '#EAE6DA',
        marginBottom: 24,
    },
    guidedPrompt: {
        flexDirection: 'row',
        marginBottom: 32,
    },
    promptLabel: {
        fontSize: 10,
        fontWeight: '700',
        color: '#A3A3A3',
        letterSpacing: 1.5,
        marginBottom: 6,
    },
    promptText: {
        fontSize: 18,
        fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
        fontStyle: 'italic',
        color: '#826930',
        lineHeight: 24,
    },
    saveButton: {
        backgroundColor: '#A0834B',
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 18,
        shadowColor: '#A0834B',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    saveButtonText: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: '700',
    },
    footer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingBottom: 24,
        alignItems: 'center',
    },
    footerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    footerText: {
        fontSize: 8,
        fontWeight: '700',
        color: '#A3A3A3',
        letterSpacing: 1.5,
        marginLeft: 6,
    },
    footerTextRight: {
        fontSize: 8,
        fontWeight: '700',
        color: '#A3A3A3',
        letterSpacing: 1.5,
    }
});
